### ISSUE TITLE
Arcface checkpoint

### ISSUE THREAD

**Issue by wkyhit** [shivangi-aneja/TAFIM#1]
Hi aneja, Thanks for your amazing contribution. I would like to perform an attack on SimSwap, but I am having some problems with the format of the Arcface checkpoint provided by the SimSwap author as a tar file. Could you kindly provide me with the arcface.pth file as shown in your project configuration. Thanks a lot!

**Comment by shivangi-aneja** [comment]
Hi.
The link to all the pretrained checkpoints is already provided in the [project readme](https://github.com/shivangi-aneja/TAFIM#pre-trained-models) in the section "Pre-trained Models".
Nevertheless, it can be downloaded from [here](https://drive.google.com/drive/folders/1ta6CZ_WSXudf7Zp7zw3mrw1QRCTaDD3M). Hope it helps.

**Comment by wkyhit** [comment]
> Hi. The link to all the pretrained checkpoints is already provided in the [project readme](https://github.com/shivangi-aneja/TAFIM#pre-trained-models) in the section "Pre-trained Models". Nevertheless, it can be downloaded from [here](https://drive.google.com/drive/folders/1ta6CZ_WSXudf7Zp7zw3mrw1QRCTaDD3M). Hope it helps.

**Comment by wkyhit** [comment]
Thanks for your reply! I have fixed out this issue.
